"""added password table

Revision ID: 831757e72482
Revises: 2941e661a071
Create Date: 2023-10-05 09:42:03.217420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831757e72482'
down_revision = '2941e661a071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
