"""create database

Revision ID: a72e2aa7e0df
Revises: 
Create Date: 2023-10-06 13:16:04.344051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a72e2aa7e0df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('event_time', sa.String(), nullable=True),
    sa.Column('arrival_time', sa.String(), nullable=True),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first', sa.String(), nullable=False),
    sa.Column('last', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('is_balance', sa.Boolean(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('password',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('practice_time', sa.String(), nullable=True),
    sa.Column('arrival_time', sa.String(), nullable=True),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('isparent', sa.Boolean(), nullable=False),
    sa.Column('isadmin', sa.Boolean(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dancers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first', sa.String(), nullable=False),
    sa.Column('last', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('emergency_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('length(bio) >= 50'),
    sa.ForeignKeyConstraint(['emergency_id'], ['emergencies.id'], name=op.f('fk_dancers_emergency_id_emergencies')),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], name=op.f('fk_dancers_parent_id_parents')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('event_dancer',
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('dancer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dancer_id'], ['dancers.id'], name=op.f('fk_event_dancer_dancer_id_dancers')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_dancer_event_id_events'))
    )
    op.create_table('practice_dancer',
    sa.Column('practice_id', sa.Integer(), nullable=True),
    sa.Column('dancer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dancer_id'], ['dancers.id'], name=op.f('fk_practice_dancer_dancer_id_dancers')),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], name=op.f('fk_practice_dancer_practice_id_practices'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('practice_dancer')
    op.drop_table('event_dancer')
    op.drop_table('dancers')
    op.drop_table('users')
    op.drop_table('practices')
    op.drop_table('password')
    op.drop_table('parents')
    op.drop_table('events')
    op.drop_table('emergencies')
    # ### end Alembic commands ###
