"""removed userid columne

Revision ID: ed4e5d6df4c3
Revises: 25b6779d0ade
Create Date: 2023-09-24 17:04:14.276847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed4e5d6df4c3'
down_revision = '25b6779d0ade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('userid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userid', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
